- sources:
  - marketwatch.com
  - investopedia.com
  - seekingalpha.com
  - xe.com
  - thestreet.com
  - financialpost.com
  - investing.com
  - kiplinger.com
  - benzinga.com
  - thisismoney.co.uk
  - cityam.com
  - daveramsey.com
  - fin24.com
  - smartasset.com
  - investorplace.com
  - institutionalinvestor.com
  - ritholtz.com
  - marketrealist.com
  - pionline.com
  - efinancialcareers.com
  - marketoracle.co.uk
  - moneymorning.com
  - financial-planning.com
  - citywire.co.uk
  - wealthmanagement.com
  - investmentwatchblog.com
  - moneytalksnews.com
  - morningstar.co.uk
  - insidermonkey.com
  - risk.net
  - realclearmarkets.com
  - financialsamurai.com
  - worldfinance.com
  - armstrongeconomics.com
  - savingadvice.com
  - fool.co.uk
  - elliottwave.com
  - simplywall.st
  - kitces.com
  - etfdailynews.com
  - investmentweek.co.uk
  - globalcapital.com
  - interest.co.nz
  - ai-cio.com
  - fool.ca
  - learnbonds.com
  - wallstreetdaily.com
  - abladvisor.com
  - fool.com.au
  - investmentexecutive.com
  - investmentu.com
  - finanzen.ch
  - financeasia.com
  - mybudget360.com
  - wallstreetpit.com
  - swfinstitute.org
  - wealthdaily.com
  - waterstechnology.com
  - smallcaps.com.au
  - finews.asia
  - marketsmedia.com
  - moneymanagement.com.au
  - smarteranalyst.com
  - moneyobserver.com
  - trustnet.com
  - themiddlemarket.com
  - finews.com
  - insidefutures.com
  - stockmarketwire.com
  - dailyreckoning.com.au
  - thetradenews.com
  - equitymaster.com
  - financialreporter.co.uk
  - ringgitplus.com
  - hedgeco.net
  - brokernews.com.au
  - theadviser.com.au
  - cnafinance.com
  - asianinvestor.net
  - dailyalts.com
